Add fr glossary
reactivemanifesto/reactivemanifesto pull request #130
Opened 2020-01-26 15:57 UTC by Dufgui

2020-01-29 07:36 UTC, skyluc commented
A bit busy for a couple of days, but I will look at this on Friday.

2020-02-04 08:12 UTC, jboner commented
@skyluc Did you have a chance to review this PR?

2020-03-09 15:51 UTC, Dufgui commented
any news? @skyluc ?

2020-03-12 11:10 UTC, skyluc requested changes
Let me start by saying that this is good work. I know how hard this kind of translation can be.
I found a few problems and typos.

One bigger problem I think, is the translation of the link anchor ids. I think those anchor ids should stay being in English, so the same anchors are used in all glossary translation.
Also, they are currently only translated in the glossary file, not in the manifesto file.

The items under 'other suggestions:' are just that, suggestions that I don't feel strongly about.

2020-03-12 11:10 UTC, skyluc commented on glossary.fr.md
> +The ability of a [système](#Système) to make use of more computing [ressources](#Ressource) in order to increase its performance is measured by the ratio of throughput gain to resource increase. A pe
This section was not translated.

2020-04-27 15:07 UTC, jboner commented on glossary.fr.md
> +The ability of a [système](#Système) to make use of more computing [ressources](#Ressource) in order to increase its performance is measured by the ratio of throughput gain to resource increase. A pe
Ok. Probably an oversight. @Dufgui can you add it? Or any other takers? @skyluc?

2020-08-14 07:41 UTC, Dufgui commented
Hello, sorry for the delay, but all reviews/remarks are now take account.

2020-08-14 17:35 UTC, jboner commented
Thanks a lot. 
@skyluc Can you review these changes?

2020-11-20 08:17 UTC, Dufgui commented
please reaview @skyluc  ;o)

2020-11-20 15:37 UTC, adriaanm commented on README.fr.md
> +Des systèmes développés selon ces directives sont plus flexibles, à couplage faible et [extensibles](/fr/glossary#Scalabilité). Cela les rend plus simples à développer et plus propices au changement.
The translated links seem inconsistent with the translated glossary, which leaves the anchor names in English, so perhaps just leave them in English here too? I'm not familiar with how these pages are generated, but I assume the link `[...](/fr/glossary#Scalabilité)` needs to match up with the `name="Scalability"` [below](https://github.com/reactivemanifesto/reactivemanifesto/pull/130/files#diff-61d7c8074220aea1e6b6e026801316b2315f03add939dcce0d6c7b06531b906cR87)

2020-11-20 15:38 UTC, adriaanm commented on README.fr.md
> +Des systèmes développés selon ces directives sont plus flexibles, à couplage faible et [extensibles](/fr/glossary#Scalabilité). Cela les rend plus simples à développer et plus propices au changement.
Concretely:

```suggestion
Des systèmes développés selon ces directives sont plus flexibles, à couplage faible et [extensibles](/fr/glossary#Scalability). Cela les rend plus simples à développer et plus propices au changement. Ils ont une plus grande tolérance vis-à-vis des [erreurs](/fr/glossary#Failure), et en cas d’erreur, réagissent de façon plus élégante, évitant ainsi des pannes catastrophiques. Ayant des temps de réponse rapide, les systèmes réactifs permettent aux [utilisateurs](/fr/glossary#User) une interaction accrue et ainsi une plus grande satisfaction.
```

2020-11-21 08:34 UTC, jboner commented
Thanks, @Dufgui, and @adriaanm. Merging.

2020-11-21 08:34 UTC, merged

2020-11-21 08:35 UTC, jboner commented
@rasummer Can you update the site with the new French glossary?

2020-11-30 17:41 UTC, rasummer commented
@jboner sorry for delayed response, I've been on vacation. Yes I will add to list and let you know once done.

2020-12-17 17:06 UTC, rasummer commented
This has been updated on the website